FROM maven:3-openjdk-8 AS builder

WORKDIR /git
RUN git clone https://github.com/fgiorgetti/qpid-dispatch-samples.git && \
    cd qpid-dispatch-samples && \
    mvn clean package

FROM openjdk:8-alpine
WORKDIR /amqpcamelspring
COPY --from=builder /git/qpid-dispatch-samples/amqpcamelspring/target/amqp-camel-spring-1.0-SNAPSHOT.jar ./
ENV CLASSPATH='/amqpcamelspring/*'
